config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :car_categories
  resources :subsidiaries, only: %i[index show new create edit update]
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    resources :car_rentals, only: [ :new, :create]
    get 'search', on: :collection
  end

  resources :car_rentals, only: [] do
    post 'finish', on: :member
  end
  
  resources :clients, only: [:index, :show, :new, :create]
  resources :cars, only: [:index, :show, :new, :create] do
    post 'maintanance', on: :member
    post 'available', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index show create]
    end
  end
end

app/models/subsidiary.rb
class Subsidiary < ApplicationRecord
  validates :name, :cnpj, :address, presence: true
  validates :cnpj, uniqueness: true
  validates :cnpj, length: { is: 18 }

  validate :cnpj_can_have_13_type_of_characters
  validate :cnpj_must_be_valid

  private

  def cnpj_can_have_13_type_of_characters
    return if cnpj.blank?
    return if cnpj.length != 18
    if cnpj.count("0-9") != 14 || cnpj.count(".") != 2 || cnpj.count("/") != 1 || cnpj.count("-") != 1
      errors.add(:cnpj, 'os caracteres aceitos para CNPJ são: números(0 a 9), ponto(.), barra(/) e traço(-)')
    end
  end

  def cnpj_must_be_valid
    return if cnpj.blank?
    return if CNPJ.valid?(cnpj, strict: true)
    
    errors.add(:cnpj, :invalid)
  end
end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :show, :new, :create, :edit, :update ]

  def index
    @subsidiaries = Subsidiary.all
  end

  def show
    @subsidiary = Subsidiary.find(params[:id])    
  end

  def new
    @subsidiary = Subsidiary.new
  end

  def create
    @subsidiary = Subsidiary.new(subsidiary_params)
    if @subsidiary.save
      redirect_to @subsidiary, notice: 'Filial criada com sucesso!'
    else
      render :new
    end
  end

  def edit
    @subsidiary = Subsidiary.find(params[:id])
  end

  def update
    @subsidiary = Subsidiary.find(params[:id])
    if @subsidiary.update(subsidiary_params)
      redirect_to @subsidiary
    else
      render :edit
    end
  end

  private

  def subsidiary_params
    params.require(:subsidiary)
          .permit(:name, :cnpj, :address)
  end
end

app/views/subsidiaries/_form.html.erb
<% @subsidiary.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: @subsidiary, local: true do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/subsidiaries/edit.html.erb
<h1>Atualização de filiais</h1>

<%= render partial: 'form', locals: { subsidiary: @subsidiary } %>

app/views/subsidiaries/index.html.erb
<h1>Filiais</h1>

<%= link_to 'Voltar', root_path %>

<%= link_to 'Registrar uma nova filial', new_subsidiary_path %>

<% @subsidiaries.each do |subsidiary| %>
  <h3><%= link_to subsidiary.name, subsidiary %></h3>
  <p><%= subsidiary.address %></p>
<% end %>

<% if @subsidiaries.empty? %>
  <h3>Nenhuma filial cadastrada</h3>
<% end %>

app/views/subsidiaries/new.html.erb
<% @subsidiary.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: @subsidiary, local: true do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/subsidiaries/show.html.erb
<%= link_to 'Voltar', subsidiaries_path %>

<%= link_to 'Editar', edit_subsidiary_path(@subsidiary) %>

<h1><%= @subsidiary.name %></h1>
<dl>
  <dt><%= Subsidiary.human_attribute_name(:cnpj) %></dt>
  <dd><%= @subsidiary.cnpj %></dd>
  <dt><%= Subsidiary.human_attribute_name(:address) %></dt>
  <dd><%= @subsidiary.address %></dd>
</dl>