config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :car_categories
  resources :subsidiaries, only: %i[index show new create edit update]
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    resources :car_rentals, only: [ :new, :create]
    get 'search', on: :collection
  end

  resources :car_rentals, only: [] do
    post 'finish', on: :member
  end
  
  resources :clients, only: [:index, :show, :new, :create]
  resources :cars, only: [:index, :show, :new, :create] do
    post 'maintanance', on: :member
    post 'available', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index show create]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #babysteps
  def index
  end
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= current_user.name %>
  <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Entrar', new_user_session_path %>
<% end %>

<header>
  <h1 class="title">Rental Cars</h1>
  <h2>Bem vindo ao sistema de gestão de locação</h2>
</header>

<% if user_signed_in? %>
  <%= link_to 'Categorias', car_categories_path %>
  <%= link_to 'Filiais', subsidiaries_path %>
  <%= link_to 'Modelos de carro', car_models_path %>
  <%= link_to 'Locações', rentals_path %>
  <%= link_to 'Clientes', clients_path %>
  <%= link_to 'Carros', cars_path %>
<% end %>