config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :car_categories
  resources :subsidiaries, only: %i[index show new create edit update]
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    resources :car_rentals, only: [ :new, :create]
    get 'search', on: :collection
  end

  resources :car_rentals, only: [] do
    post 'finish', on: :member
  end
  
  resources :clients, only: [:index, :show, :new, :create]
  resources :cars, only: [:index, :show, :new, :create] do
    post 'maintanance', on: :member
    post 'available', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index show create]
    end
  end
end

app/models/car_category.rb
class CarCategory < ApplicationRecord
  has_many :car_models
  has_many :cars, through: :car_models
  
  validates :name, :daily_rate, :car_insurance, 
            :third_party_insurance, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :daily_rate, :car_insurance, 
            :third_party_insurance, numericality: {:greater_than_or_equal_to => 0}

  def daily_price
    daily_rate + car_insurance + third_party_insurance
  end
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :show, :new, :create, :edit, :update ]
  
  def index
    @car_categories = CarCategory.all
  end

  def show
    @car_category = CarCategory.find(params[:id]) #params é um HASH    
  end

  def new
    @car_category = CarCategory.new    
  end

  def create
    @car_category = CarCategory.new(car_category_params)
    if @car_category.save
      redirect_to @car_category, notice: 'Categoria de carro criada com sucesso!'
    else
      render :new
    end 
  end

  def edit
    @car_category = CarCategory.find(params[:id])
  end

  def update
    @car_category = CarCategory.find(params[:id])
    if @car_category.update(car_category_params)
      redirect_to @car_category
    else
      render :edit
    end
  end

  def destroy
    @car_category = CarCategory.find(params[:id])
    @car_category.destroy
    redirect_to car_categories_path
  end

  private

  def car_category_params
    params.require(:car_category)
          .permit(:name, :daily_rate, :car_insurance, :third_party_insurance)
  end
end

app/views/car_categories/_form.html.erb
<% car_category.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: car_category, local: true do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :daily_rate %>
    <%= f.number_field :daily_rate, min: 0 %>
  </div>
  <div>
    <%= f.label :car_insurance %>
    <%= f.number_field :car_insurance, min: 0 %>
  </div>
  <div>
    <%= f.label :third_party_insurance %>
    <%= f.number_field :third_party_insurance, min: 0 %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>  
<% end %>

app/views/car_categories/edit.html.erb
<h1>Atualização de categorias de carro</h1>

<%= render partial: 'form', locals: { car_category: @car_category } %>

app/views/car_categories/index.html.erb
<h1>Categorias de carro</h1>

<%= link_to 'Voltar', root_path %>

<%= link_to 'Registrar uma nova categoria', new_car_category_path %>

<% @car_categories.each do |category| %>
  <h3><%= link_to category.name, category %></h3>
<% end %>

<% if @car_categories.empty? %>
  <h3>Nenhuma categoria cadastrada</h3>
<% end %>

app/views/car_categories/new.html.erb
<h1>Criar uma categoria de carro</h1>

<%= render partial: 'form', locals: { car_category: @car_category } %>

app/views/car_categories/show.html.erb
<%= link_to 'Voltar', car_categories_path %>

<%= link_to 'Editar', edit_car_category_path(@car_category) %>

<h1><%= @car_category.name %></h1>
<dl>
  <dt><%= CarCategory.human_attribute_name(:daily_rate) %></dt>
  <dd><%= number_to_currency @car_category.daily_rate %></dd>
  <dt><%= CarCategory.human_attribute_name(:car_insurance) %></dt>
  <dd><%= number_to_currency @car_category.car_insurance %></dd>
  <dt><%= CarCategory.human_attribute_name(:third_party_insurance) %></dt>
  <dd><%= number_to_currency @car_category.third_party_insurance %></dd>
</dl>

<h3>Modelos de carro</h3>

<%= render @car_category.car_models %>

<%= link_to 'Apagar', car_category_path(@car_category), method: :delete,
    data: { confirm: 'Tem certeza que deseja apagar?' } %>