config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :car_categories
  resources :subsidiaries, only: %i[index show new create edit update]
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    resources :car_rentals, only: [ :new, :create]
    get 'search', on: :collection
  end

  resources :car_rentals, only: [] do
    post 'finish', on: :member
  end
  
  resources :clients, only: [:index, :show, :new, :create]
  resources :cars, only: [:index, :show, :new, :create] do
    post 'maintanance', on: :member
    post 'available', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index show create]
    end
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :client
  belongs_to :car_category
  belongs_to :user
  has_one :car_rental
  validates :start_date, :end_date, presence: true

  before_create :generate_token

  # def scheduled?
  #   car_rental.blank?
  # end

  # def in_progress?
  #   car_rental && car_rental.end_date.blank?
  # end

  # def finalized?
  #   car_rental && car_rental.end_date.present?
  # end

  def total
    
    number_of_days_rented = end_date - start_date

    number_of_days_rented * car_category.daily_price
  end

  private

  def generate_token
    self.token = SecureRandom.alphanumeric(6).upcase
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create] 
  
  def index
    @rentals = Rental.all
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def new
    @rental = Rental.new
    @clients = Client.all
    @car_categories = CarCategory.all 
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    if @rental.save
      redirect_to @rental, notice: 'Agendamento realizado com sucesso!'
    else
      @clients = Client.all
      @car_categories = CarCategory.all
      render :new
    end
  end

  def search
    @rentals = Rental.where('token LIKE ?', "%#{params[:q]}%")
    render :index
  end

  private

  def rental_params 
    params.require(:rental)
          .permit(:start_date, :end_date, :client_id, :car_category_id)
  end
end

app/views/rentals/_rental.html.erb
<div>
  <dl>
    <dt>Token</dt>
    <dd><%= rental.token %></dd>
    <dt><%= Rental.human_attribute_name :start_date %></dt>
    <dd><%= l rental.start_date %></dd>
    <dt><%= Rental.human_attribute_name :end_date %></dt>
    <dd><%= l rental.end_date %></dd>
    <dt><%= Rental.human_attribute_name :client %></dt>
    <dd><%= rental.client.name %></dd>
    <dd><%= rental.client.cpf %></dd>
    <dd><%= rental.client.email %></dd>
    <dt><%= Rental.human_attribute_name :car_category %></dt>
    <dd><%= rental.car_category.name %></dd>
    <dt><%= Rental.human_attribute_name :total %></dt>
    <dd><%= number_to_currency rental.total %></dd>
    <dt><%= Rental.human_attribute_name :user %></dt>
    <dd><%= rental.user.email %></dd>
    <%= link_to 'Ver detalhes', rental %>
  </dl>
</div>

app/views/rentals/index.html.erb
<h1>Locações</h1>

<%= link_to 'Voltar', root_path %>

<%= link_to 'Agendar nova locação', new_rental_path %>

<%= form_with url: search_rentals_path, method: :get, local: true do |f| %>
  <%= f.label :q, 'Busca de locação' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<%= render @rentals %>

<% if @rentals.empty? %>
  <h3>Nenhuma locação agendada</h3>
<% end %>

app/views/rentals/new.html.erb
<% @rental.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: @rental, local: true do |f| %>
  <%= f.label :start_date %>
  <%= f.date_field :start_date %>
  <%= f.label :end_date %>
  <%= f.date_field :end_date %>
  <%= f.label :client_id %>
  <%= f.collection_select :client_id, @clients, :id, :information %>
  <%= f.label :car_category_id %>
  <%= f.collection_select :car_category_id, @car_categories, :id, :name %>
  <%= f.submit 'Agendar' %>
<% end %>

app/views/rentals/show.html.erb
<h1>Locação</h1>
<h2>Dados do Agendamento</h2>

<div>
  <dl>
    <dt>Token</dt>
    <dd><%= @rental.token %></dd>
    <dt><%= Rental.human_attribute_name :start_date %></dt>
    <dd><%= l @rental.start_date %></dd>
    <dt><%= Rental.human_attribute_name :end_date %></dt>
    <dd><%= l @rental.end_date %></dd>
    <dt><%= Rental.human_attribute_name :client %></dt>
    <dd><%= @rental.client.name %></dd>
    <dd><%= @rental.client.cpf %></dd>
    <dd><%= @rental.client.email %></dd>
    <dt><%= Rental.human_attribute_name :car_category %></dt>
    <dd><%= @rental.car_category.name %></dd>
    <dt><%= Rental.human_attribute_name :total %></dt>
    <dd><%= number_to_currency @rental.total %></dd>
    <dt><%= Rental.human_attribute_name :user %></dt>
    <dd><%= @rental.user.email %></dd>
  </dl>
</div>

<% if @rental.car_rental %>
  <h2>Locação Iniciada</h2>

  Carro Escolhido: <%= @rental.car_rental.car.description %>
  
  CNH do Condutor: <%= @rental.car_rental.driver_license_number %>
  
  Usuário: <%= @rental.car_rental.user.email %>
  
  Início da Locação: <%= l @rental.car_rental.start_date %>

  <p>Em andamento</p>
<% else %>
  
  <%= link_to 'Iniciar locação', new_rental_car_rental_path(@rental.id) %>

<% end %>